-- Clean slate (handy during dev)
SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS shipment_items;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS pickup_points;
DROP TABLE IF EXISTS products;
SET REFERENTIAL_INTEGRITY TRUE;

-- Products
CREATE TABLE products
(
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    version        BIGINT         NOT NULL DEFAULT 0,
    name           VARCHAR(100)   NOT NULL,
    description    VARCHAR(500)   NOT NULL,
    category       VARCHAR(100)   NOT NULL,
    brand          VARCHAR(100),
    sku            VARCHAR(50)    NOT NULL UNIQUE,
    stock_quantity INT            NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    reorder_level  INT            NOT NULL DEFAULT 5 CHECK (reorder_level >= 0),
    supplier       VARCHAR(150),
    weight_grams   DECIMAL(8, 2),
    dimensions_cm  VARCHAR(50),
    color          VARCHAR(50),
    release_date   DATE,
    price          DECIMAL(12, 2) NOT NULL CHECK (price >= 0),
    discount       DECIMAL(5, 2)           DEFAULT 0 CHECK (discount >= 0 AND discount <= 100),
    rating         DECIMAL(3, 2)           DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    active         BOOLEAN        NOT NULL DEFAULT TRUE
);

-- Countries
CREATE TABLE countries
(
    country_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso2         CHAR(2)      NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_iso2 UNIQUE (iso2),
    CONSTRAINT uq_country UNIQUE (country_name)
);

-- Cities
CREATE TABLE cities
(
    city_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT       NOT NULL,
    city       VARCHAR(100) NOT NULL,
    CONSTRAINT uq_city UNIQUE (country_id, city),
    CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES countries (country_id)
);

-- Pick-up points (click & collect)
CREATE TABLE pickup_points
(
    pickup_point_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT        NOT NULL DEFAULT 0,
    name            VARCHAR(100)  NOT NULL,
    city_id         BIGINT        NOT NULL,
    latitude        DECIMAL(9, 6) NOT NULL, -- ~10cm precision
    longitude       DECIMAL(9, 6) NOT NULL,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_pickup_point UNIQUE (name, city_id),
    CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES cities (city_id)
);

-- Customers
CREATE TABLE customers
(
    customer_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                   BIGINT       NOT NULL DEFAULT 0,
    first_name                VARCHAR(50)  NOT NULL,
    last_name                 VARCHAR(50)  NOT NULL,
    email                     VARCHAR(320) NOT NULL,
    phone                     VARCHAR(25)  NOT NULL,
    active                    BOOLEAN      NOT NULL DEFAULT TRUE,
    preferred_pickup_point_id BIGINT,
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT fk_customer_pref_pp
        FOREIGN KEY (preferred_pickup_point_id) REFERENCES pickup_points (pickup_point_id)
);

-- Orders
CREATE TABLE orders
(
    order_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                    BIGINT      NOT NULL DEFAULT 0,
    status                     VARCHAR(32) NOT NULL,
    customer_id                BIGINT      NOT NULL,
    deliver_to_pickup_point_id BIGINT      NOT NULL,
    created                    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated               TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_order_status CHECK (status IN (
                                                 'draft', 'pending', 'processing', 'cancelled', 'shipped',
                                                 'partially_shipped'
        )),
    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_order_pickup
        FOREIGN KEY (deliver_to_pickup_point_id) REFERENCES pickup_points (pickup_point_id)
);

-- Order items (price & name are snapshots)
CREATE TABLE order_items
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT         NOT NULL DEFAULT 0,
    order_id      BIGINT         NOT NULL,
    product_id    BIGINT         NOT NULL,
    product_name  VARCHAR(100)   NOT NULL,
    product_price DECIMAL(12, 2) NOT NULL CHECK (product_price >= 0),
    quantity      INT            NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

-- Shipments (an order may have multiple shipments)
CREATE TABLE shipments
(
    shipment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT      NOT NULL DEFAULT 0,
    status       VARCHAR(32) NOT NULL,
    order_id     BIGINT      NOT NULL,
    created      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_shipment_status CHECK (status IN (
                                                    'draft', 'pending', 'collecting', 'transporting', 'at_pickup_point',
                                                    'delivered', 'returned'
        )),
    CONSTRAINT fk_shipment_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE
);

-- Shipment items (ties shipment to specific order items)
CREATE TABLE shipment_items
(
    shipment_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          BIGINT NOT NULL DEFAULT 0,
    shipment_id      BIGINT NOT NULL,
    order_item_id    BIGINT NOT NULL,
    quantity         INT    NOT NULL CHECK (quantity > 0),
    remaining        INT    NOT NULL CHECK (remaining >= 0),
    comment          VARCHAR(100),
    CONSTRAINT fk_si_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id) ON DELETE CASCADE,
    CONSTRAINT fk_si_oi FOREIGN KEY (order_item_id) REFERENCES order_items (order_item_id) ON DELETE CASCADE,
    CONSTRAINT ck_si_remaining CHECK (remaining <= quantity)
);

-- Helpful indexes
--CREATE INDEX idx_orders_customer ON orders (customer_id);
--CREATE INDEX idx_orders_status ON orders (status);
--CREATE INDEX idx_shipments_order ON shipments (order_id);
--CREATE INDEX idx_pickup_city_name ON pickup_points (city, name);